#!/usr/bin/env bash

# Convert pdf files to cbz files by tracing all images in the pdf file with
# imagemagick and zipping the image files together. This is only necessary if
# there are other elements in the pdf than text. Otherwise it is possible to
# just extract all images from the pdf instead of tracing them.

# Variables
DENSITY=300
QUALITY=80
FILE_EXTENSION="jpg"
OPERATION_ID=$((1 + $RANDOM % 1000))
TMP_DIR="pdf2cbz-${OPERATION_ID}"

# Creating temporary dir
mkdir "$TMP_DIR"

# Convert to images
echo "Converting pdf to images"
NUM_OF_PAGES=$(pdftk "$1" dump_data | grep "NumberOfPages" | cut -d" " -f2)
for ((i = 0 ; i < $NUM_OF_PAGES ; i++)); do
    index=$(printf '%03d' $i)
    convert -density $DENSITY -quality $QUALITY "$1[$i]" "$TMP_DIR/page-$index.$FILE_EXTENSION"
done

# Zipping files
echo "Zipping files"
zip "$2" "$TMP_DIR"/*

# Cleanup
rm -rf "$TMP_DIR"
